### ISSUE TITLE
trait not found

### ISSUE THREAD

**Issue by bogdanr2000** [sameday-courier/opencart-plugin#9]
hi,

i am using this this extension, with php 7.4 and oc 3;
i have the following error 
PHP Fatal error:  Trait "Sameday\Objects\Traits\SamedayObjectCodeTrait" not found in /system/library/sameday-php-sdk/src/Sameday/Objects/Service/ServiceObject.php on line 14

any help is appreciated; thanks

**Comment by Soptareanu** [comment]
This bug was fixed.
